structure(list(url = "https://HOSTNAME/access/api/v1/tokens?expires_in=61", 
    status_code = 401L, headers = structure(list(date = "Mon, 23 Aug 2021 10:23:42 GMT", 
        `content-type` = "application/json;charset=UTF-8", `content-length` = "117", 
        connection = "keep-alive", `cache-control` = "no-cache, no-store, max-age=0, must-revalidate", 
        expires = "0", pragma = "no-cache", `x-content-type-options` = "nosniff", 
        `x-frame-options` = "DENY", `x-jfrog-version` = "JFrog Access/7.23.1", 
        `x-xss-protection` = "1; mode=block", `strict-transport-security` = "max-age=15724800; includeSubDomains"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 401L, version = "HTTP/1.1", 
        headers = structure(list(date = "Mon, 23 Aug 2021 10:23:42 GMT", 
            `content-type` = "application/json;charset=UTF-8", 
            `content-length` = "117", connection = "keep-alive", 
            `cache-control` = "no-cache, no-store, max-age=0, must-revalidate", 
            expires = "0", pragma = "no-cache", `x-content-type-options` = "nosniff", 
            `x-frame-options` = "DENY", `x-jfrog-version` = "JFrog Access/7.23.1", 
            `x-xss-protection` = "1; mode=block", `strict-transport-security` = "max-age=15724800; includeSubDomains"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("{\n  \"errors\" : [ {\n    \"code\" : \"UNAUTHORIZED\",\n    \"message\" : \"Bearer authentication failed, invalid token\"\n  } ]\n}"), 
    date = structure(1629714222, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 0.030646, 
    connect = 0.052231, pretransfer = 0.109437, starttransfer = 0.135304, 
    total = 0.135343)), class = "response")
